const PRESETS = {
  math: { name: 'Math', icon: '🔢', categories: { red: 'addition', blue: 'fraction', green: 'division', yellow: null } },
  geo:  { name: 'Geography', icon: '🌍', categories: { red: 'flag', blue: 'country', green: 'ocean', yellow: null } },
  sci:  { name: 'Science', icon: '🔬', categories: { red: 'biology', blue: 'physics', green: 'chemistry', yellow: null } },
  nature: { name: 'Nature', icon: '🌿', categories: { red: 'animals', blue: 'plants', green: 'earth', yellow: 'human-body' } },
};

const CATEGORY_NAMES = {
  addition: 'Addition', fraction: 'Fraction', division: 'Division',
  flag: 'Flag', country: 'Country', ocean: 'Ocean',
  biology: 'Biology', physics: 'Physics', chemistry: 'Chemistry',
  animals: 'Animals & Wildlife', plants: 'Plants & Trees',
  earth: 'Earth & Space', 'human-body': 'Human Body & Health',
};

const QUESTION_BANKS = {
  fraction: [
    { text: "1/2 + 1/4 = ?", options: ["1/4", "3/4", "2/3", "1"], answerIndex: 1 },
    { text: "3/4 - 1/4 = ?", options: ["1/2", "1/4", "1", "3/8"], answerIndex: 0 },
    { text: "Which is larger?", options: ["1/3", "1/4", "1/5", "1/6"], answerIndex: 0 },
    { text: "0.5 as a fraction", options: ["1/3", "1/2", "2/5", "3/4"], answerIndex: 1 },
    { text: "25% as a fraction", options: ["1/2", "1/5", "1/4", "1/3"], answerIndex: 2 },
    { text: "2/3 of 9 = ?", options: ["4", "5", "6", "7"], answerIndex: 2 },
    { text: "1/2 + 1/2 = ?", options: ["1/4", "1/2", "3/4", "1"], answerIndex: 3 },
    { text: "5/8 - 3/8 = ?", options: ["1/4", "2/8", "1/2", "3/4"], answerIndex: 0 },
    { text: "2/5 + 1/5 = ?", options: ["2/10", "3/5", "3/10", "1/5"], answerIndex: 1 },
    { text: "Which equals 0.75?", options: ["1/4", "3/4", "2/3", "5/8"], answerIndex: 1 },
  ],
  flag: [
    { text: "Which country's flag has a red maple leaf?", options: ["USA", "Canada", "UK", "Australia"], answerIndex: 1 },
    { text: "Which country's flag has stars and stripes?", options: ["Canada", "UK", "USA", "Brazil"], answerIndex: 2 },
    { text: "Which country's flag is a red circle on white?", options: ["China", "Japan", "South Korea", "Thailand"], answerIndex: 1 },
    { text: "Which country's flag has a white cross on red?", options: ["Sweden", "Norway", "Switzerland", "Denmark"], answerIndex: 2 },
    { text: "Which country's flag has a Union Jack?", options: ["USA", "Australia", "Ireland", "France"], answerIndex: 1 },
    { text: "Which country's flag is green, white, and orange?", options: ["Italy", "Ireland", "France", "India"], answerIndex: 1 },
    { text: "Which country's flag has a yellow star on red?", options: ["China", "Vietnam", "Russia", "Cuba"], answerIndex: 1 },
    { text: "Which country's flag has a blue and yellow bicolor?", options: ["Poland", "Ukraine", "Romania", "Sweden"], answerIndex: 1 },
    { text: "Which country's flag has horizontal blue, white, red stripes?", options: ["Netherlands", "France", "Italy", "Germany"], answerIndex: 0 },
    { text: "Which country's flag has a white crescent and star on green?", options: ["Saudi Arabia", "Pakistan", "Turkey", "Algeria"], answerIndex: 1 },
  ],
  country: [
    { text: "What is the capital of France?", options: ["London", "Paris", "Berlin", "Madrid"], answerIndex: 1 },
    { text: "What is the capital of Japan?", options: ["Seoul", "Beijing", "Tokyo", "Bangkok"], answerIndex: 2 },
    { text: "What is the largest country by area?", options: ["USA", "China", "Russia", "Canada"], answerIndex: 2 },
    { text: "Which country has the most people?", options: ["China", "India", "USA", "Indonesia"], answerIndex: 1 },
    { text: "What is the capital of Egypt?", options: ["Cairo", "Lagos", "Nairobi", "Casablanca"], answerIndex: 0 },
    { text: "Which continent is the Amazon in?", options: ["Asia", "Africa", "South America", "Australia"], answerIndex: 2 },
    { text: "What is the longest river?", options: ["Amazon", "Nile", "Mississippi", "Yangtze"], answerIndex: 1 },
    { text: "What is the capital of Australia?", options: ["Sydney", "Melbourne", "Canberra", "Perth"], answerIndex: 2 },
    { text: "How many continents are there?", options: ["5", "6", "7", "8"], answerIndex: 2 },
    { text: "Which country is both in Europe and Asia?", options: ["Greece", "Turkey", "Egypt", "Iran"], answerIndex: 1 },
  ],
  ocean: [
    { text: "What is the largest ocean?", options: ["Atlantic", "Indian", "Pacific", "Arctic"], answerIndex: 2 },
    { text: "What is the deepest ocean?", options: ["Indian", "Pacific", "Atlantic", "Arctic"], answerIndex: 1 },
    { text: "Which ocean is between Africa and Australia?", options: ["Pacific", "Atlantic", "Indian", "Arctic"], answerIndex: 2 },
    { text: "Which ocean is north of Russia?", options: ["Pacific", "Indian", "Atlantic", "Arctic"], answerIndex: 3 },
    { text: "What is the smallest ocean?", options: ["Indian", "Arctic", "Atlantic", "Pacific"], answerIndex: 1 },
    { text: "Which ocean surrounds Hawaii?", options: ["Indian", "Atlantic", "Arctic", "Pacific"], answerIndex: 3 },
    { text: "Which ocean is west of Europe?", options: ["Pacific", "Indian", "Arctic", "Atlantic"], answerIndex: 3 },
    { text: "Which ocean is east of Africa?", options: ["Atlantic", "Pacific", "Indian", "Arctic"], answerIndex: 2 },
    { text: "Which ocean is on the US west coast?", options: ["Atlantic", "Pacific", "Arctic", "Indian"], answerIndex: 1 },
    { text: "Which ocean is on the US east coast?", options: ["Pacific", "Atlantic", "Indian", "Arctic"], answerIndex: 1 },
  ],
  biology: [
    { text: "What is the powerhouse of the cell?", options: ["Nucleus", "Mitochondria", "Ribosome", "Membrane"], answerIndex: 1 },
    { text: "How many bones in the adult human body?", options: ["186", "196", "206", "216"], answerIndex: 2 },
    { text: "What is the largest human organ?", options: ["Liver", "Brain", "Heart", "Skin"], answerIndex: 3 },
    { text: "Plants make food through what process?", options: ["Digestion", "Photosynthesis", "Respiration", "Fermentation"], answerIndex: 1 },
    { text: "What are meat-eaters called?", options: ["Herbivores", "Omnivores", "Carnivores", "Insectivores"], answerIndex: 2 },
    { text: "What is the smallest unit of life?", options: ["Atom", "Molecule", "Cell", "Tissue"], answerIndex: 2 },
    { text: "How many chromosomes do humans have?", options: ["23", "44", "46", "48"], answerIndex: 2 },
    { text: "What blood cells fight infections?", options: ["Red", "White", "Platelets", "Plasma"], answerIndex: 1 },
    { text: "Which vitamin comes from sunlight?", options: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], answerIndex: 3 },
    { text: "What is the study of living things?", options: ["Physics", "Chemistry", "Biology", "Geology"], answerIndex: 2 },
  ],
  physics: [
    { text: "What is the speed of light approx?", options: ["3000 km/s", "300,000 km/s", "30,000 km/s", "3,000,000 km/s"], answerIndex: 1 },
    { text: "What is the unit of force?", options: ["Joule", "Newton", "Watt", "Pascal"], answerIndex: 1 },
    { text: "What keeps planets orbiting the sun?", options: ["Magnetism", "Gravity", "Friction", "Inertia"], answerIndex: 1 },
    { text: "What is the SI unit of energy?", options: ["Newton", "Watt", "Joule", "Volt"], answerIndex: 2 },
    { text: "What type of energy is stored?", options: ["Kinetic", "Potential", "Thermal", "Sound"], answerIndex: 1 },
    { text: "What is the boiling point of water in C?", options: ["50°C", "75°C", "100°C", "125°C"], answerIndex: 2 },
    { text: "Which particle has a negative charge?", options: ["Proton", "Neutron", "Electron", "Positron"], answerIndex: 2 },
    { text: "What is the freezing point of water in C?", options: ["-10°C", "0°C", "10°C", "32°C"], answerIndex: 1 },
    { text: "What is the unit of electric current?", options: ["Volt", "Ampere", "Ohm", "Watt"], answerIndex: 1 },
    { text: "What phenomenon bends light?", options: ["Reflection", "Diffraction", "Refraction", "Absorption"], answerIndex: 2 },
  ],
  chemistry: [
    { text: "What is the chemical symbol for water?", options: ["HO", "H2O", "OH2", "H2O2"], answerIndex: 1 },
    { text: "What is the chemical symbol for gold?", options: ["Go", "Gd", "Au", "Ag"], answerIndex: 2 },
    { text: "What is the pH of pure water?", options: ["5", "6", "7", "8"], answerIndex: 2 },
    { text: "What gas do plants absorb from air?", options: ["Oxygen", "Nitrogen", "CO2", "Hydrogen"], answerIndex: 2 },
    { text: "What is the lightest element?", options: ["Helium", "Hydrogen", "Lithium", "Oxygen"], answerIndex: 1 },
    { text: "What is the symbol for oxygen?", options: ["Ox", "O", "O2", "O3"], answerIndex: 1 },
    { text: "Liquid to gas is called?", options: ["Condensation", "Evaporation", "Melting", "Sublimation"], answerIndex: 1 },
    { text: "What is the symbol for iron?", options: ["Ir", "In", "Fe", "Io"], answerIndex: 2 },
    { text: "Most abundant gas in Earth's atmosphere?", options: ["Oxygen", "CO2", "Nitrogen", "Argon"], answerIndex: 2 },
    { text: "What type of bond shares electrons?", options: ["Ionic", "Covalent", "Metallic", "Hydrogen"], answerIndex: 1 },
  ],
  animals: [
    { text: "What is the largest land animal?", options: ["Elephant", "Rhino", "Hippo", "Giraffe"], answerIndex: 0, image: "assets/quiz-images/animals-q1.jpg" },
    { text: "What mammal can truly fly?", options: ["Squirrel", "Bat", "Flying Fox", "Bird"], answerIndex: 1, image: "assets/quiz-images/animals-q2.jpg" },
    { text: "What is a group of lions called?", options: ["Pack", "Herd", "Pride", "Flock"], answerIndex: 2, image: "assets/quiz-images/animals-q3.jpg" },
    { text: "Which animal is known as the king of the jungle?", options: ["Tiger", "Lion", "Bear", "Leopard"], answerIndex: 1, image: "assets/quiz-images/animals-q4.jpg" },
    { text: "What is the fastest land animal?", options: ["Lion", "Horse", "Cheetah", "Gazelle"], answerIndex: 2, image: "assets/quiz-images/animals-q5.jpg" },
    { text: "Which animal has the longest neck?", options: ["Camel", "Giraffe", "Ostrich", "Llama"], answerIndex: 1, image: "assets/quiz-images/animals-q6.jpg" },
    { text: "What is the largest species of shark?", options: ["Great White", "Tiger Shark", "Whale Shark", "Hammerhead"], answerIndex: 2, image: "assets/quiz-images/animals-q7.jpg" },
    { text: "Which animal sleeps the most?", options: ["Sloth", "Koala", "Cat", "Bat"], answerIndex: 1, image: "assets/quiz-images/animals-q8.jpg" },
    { text: "What is a baby kangaroo called?", options: ["Cub", "Joey", "Pup", "Calf"], answerIndex: 1, image: "assets/quiz-images/animals-q9.jpg" },
    { text: "Which bird cannot fly?", options: ["Eagle", "Penguin", "Sparrow", "Hawk"], answerIndex: 1, image: "assets/quiz-images/animals-q10.jpg" },
    { text: "What is the largest reptile in the world?", options: ["Crocodile", "Komodo Dragon", "Anaconda", "Turtle"], answerIndex: 0, image: "assets/quiz-images/animals-q11.jpg" },
    { text: "Which animal has black and white stripes?", options: ["Horse", "Zebra", "Tiger", "Skunk"], answerIndex: 1, image: "assets/quiz-images/animals-q12.jpg" },
    { text: "What do pandas mainly eat?", options: ["Meat", "Bamboo", "Fruit", "Fish"], answerIndex: 1, image: "assets/quiz-images/animals-q13.jpg" },
    { text: "Which animal is known for spraying a bad smell?", options: ["Badger", "Skunk", "Weasel", "Opossum"], answerIndex: 1, image: "assets/quiz-images/animals-q14.jpg" },
    { text: "What is the tallest animal on Earth?", options: ["Elephant", "Giraffe", "Camel", "Horse"], answerIndex: 1, image: "assets/quiz-images/animals-q15.jpg" },
    { text: "Which animal lives the longest?", options: ["Elephant", "Blue Whale", "Bowhead Whale", "Galapagos Tortoise"], answerIndex: 3 },
    { text: "What type of animal is a dolphin?", options: ["Fish", "Mammal", "Reptile", "Amphibian"], answerIndex: 1 },
    { text: "Which animal has three hearts?", options: ["Octopus", "Squid", "Crab", "Lobster"], answerIndex: 0 },
    { text: "What is the only mammal that can truly fly?", options: ["Bat", "Flying Squirrel", "Bird", "Pterodactyl"], answerIndex: 0 },
    { text: "Which animal changes color to blend in?", options: ["Lizard", "Chameleon", "Snake", "Frog"], answerIndex: 1 },
    { text: "What is the largest mammal in the world?", options: ["Elephant", "Blue Whale", "Giraffe", "Hippopotamus"], answerIndex: 1 },
    { text: "Which animal is known to use tools?", options: ["Dog", "Cat", "Chimpanzee", "Horse"], answerIndex: 2 },
    { text: "What is a group of fish called?", options: ["Herd", "Flock", "School", "Pack"], answerIndex: 2 },
    { text: "Which insect produces honey?", options: ["Ant", "Wasp", "Bee", "Beetle"], answerIndex: 2 },
    { text: "What do you call an animal that eats both plants and meat?", options: ["Herbivore", "Carnivore", "Omnivore", "Insectivore"], answerIndex: 2 },
  ],
  plants: [
    { text: "What process do plants use to make food?", options: ["Digestion", "Photosynthesis", "Respiration", "Fermentation"], answerIndex: 1, image: "assets/quiz-images/plants-q16.jpg" },
    { text: "What part of the plant absorbs water?", options: ["Leaves", "Stem", "Roots", "Flowers"], answerIndex: 2, image: "assets/quiz-images/plants-q17.jpg" },
    { text: "What is the tallest species of grass?", options: ["Sugar Cane", "Bamboo", "Corn", "Wheat"], answerIndex: 1, image: "assets/quiz-images/plants-q18.jpg" },
    { text: "Which part of the plant is usually colorful?", options: ["Root", "Stem", "Leaf", "Flower"], answerIndex: 3, image: "assets/quiz-images/plants-q19.jpg" },
    { text: "What do plants release during photosynthesis?", options: ["CO2", "Nitrogen", "Oxygen", "Hydrogen"], answerIndex: 2, image: "assets/quiz-images/plants-q20.jpg" },
    { text: "Which plant is known for its large yellow flower head?", options: ["Tulip", "Rose", "Sunflower", "Daisy"], answerIndex: 2, image: "assets/quiz-images/plants-q21.jpg" },
    { text: "What is the main pigment in plants that makes them green?", options: ["Carotene", "Chlorophyll", "Xanthophyll", "Melanin"], answerIndex: 1, image: "assets/quiz-images/plants-q22.jpg" },
    { text: "Which tree produces acorns?", options: ["Maple", "Oak", "Pine", "Birch"], answerIndex: 1, image: "assets/quiz-images/plants-q23.jpg" },
    { text: "What part of a tree transports water upward?", options: ["Bark", "Xylem", "Phloem", "Cambium"], answerIndex: 1, image: "assets/quiz-images/plants-q24.jpg" },
    { text: "Which plant is known for healing burns?", options: ["Mint", "Aloe Vera", "Lavender", "Rosemary"], answerIndex: 1, image: "assets/quiz-images/plants-q25.jpg" },
    { text: "What is the world's largest flower?", options: ["Sunflower", "Rafflesia", "Lotus", "Titan Arum"], answerIndex: 1, image: "assets/quiz-images/plants-q26.jpg" },
    { text: "Which plant lives for over 1000 years?", options: ["Rose", "Oak", "Bristlecone Pine", "Apple Tree"], answerIndex: 2, image: "assets/quiz-images/plants-q27.jpg" },
    { text: "What is a cone-bearing plant called?", options: ["Fern", "Moss", "Conifer", "Algae"], answerIndex: 2, image: "assets/quiz-images/plants-q28.jpg" },
    { text: "Which plant closes its leaves when touched?", options: ["Venus Flytrap", "Mimosa", "Sundew", "Cactus"], answerIndex: 1, image: "assets/quiz-images/plants-q29.jpg" },
    { text: "What is the oldest type of land plant?", options: ["Ferns", "Mosses", "Conifers", "Flowering Plants"], answerIndex: 1, image: "assets/quiz-images/plants-q30.jpg" },
    { text: "What is the process of seeds sprouting called?", options: ["Pollination", "Germination", "Fertilization", "Propagation"], answerIndex: 1 },
    { text: "Which part of a plant becomes the fruit?", options: ["Root", "Stem", "Leaf", "Ovary"], answerIndex: 3 },
    { text: "What do bees collect from flowers?", options: ["Pollen and Nectar", "Leaves", "Water", "Seeds"], answerIndex: 0 },
    { text: "Which plant grows in the desert and stores water?", options: ["Fern", "Moss", "Cactus", "Lily"], answerIndex: 2 },
    { text: "What is the study of plants called?", options: ["Zoology", "Botany", "Ecology", "Geology"], answerIndex: 1 },
    { text: "Which tree loses its leaves in autumn?", options: ["Pine", "Spruce", "Deciduous Tree", "Fir"], answerIndex: 2 },
    { text: "What gas do plants absorb from the atmosphere?", options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Argon"], answerIndex: 2 },
    { text: "Which part of a plant supports the leaves and flowers?", options: ["Root", "Stem", "Leaf", "Seed"], answerIndex: 1 },
    { text: "What are the tiny holes on leaves called?", options: ["Pores", "Stomata", "Veins", "Cells"], answerIndex: 1 },
    { text: "Which type of plant flower lives for one season?", options: ["Perennial", "Biennial", "Annual", "Evergreen"], answerIndex: 2 },
  ],
  earth: [
    { text: "What is the largest planet in our solar system?", options: ["Saturn", "Neptune", "Jupiter", "Uranus"], answerIndex: 2, image: "assets/quiz-images/earth-q31.jpg" },
    { text: "What is the closest star to Earth?", options: ["Moon", "Sun", "Sirius", "Venus"], answerIndex: 1, image: "assets/quiz-images/earth-q32.jpg" },
    { text: "What is the hottest planet in our solar system?", options: ["Mercury", "Venus", "Mars", "Jupiter"], answerIndex: 1, image: "assets/quiz-images/earth-q33.jpg" },
    { text: "What causes the tides on Earth?", options: ["Wind", "Moon's Gravity", "Earth's Rotation", "Sun's Heat"], answerIndex: 1, image: "assets/quiz-images/earth-q34.jpg" },
    { text: "What is the largest ocean on Earth?", options: ["Atlantic", "Indian", "Pacific", "Arctic"], answerIndex: 2, image: "assets/quiz-images/earth-q35.jpg" },
    { text: "What is the deepest part of the ocean called?", options: ["Abyss", "Trench", "Basin", "Ridge"], answerIndex: 1, image: "assets/quiz-images/earth-q36.jpg" },
    { text: "Which planet is known as the Red Planet?", options: ["Venus", "Mars", "Jupiter", "Saturn"], answerIndex: 1, image: "assets/quiz-images/earth-q37.jpg" },
    { text: "What type of rock forms from cooled lava?", options: ["Sedimentary", "Metamorphic", "Igneous", "Fossil"], answerIndex: 2, image: "assets/quiz-images/earth-q38.jpg" },
    { text: "What causes a rainbow?", options: ["Wind", "Rain and Sun", "Clouds", "Snow"], answerIndex: 1, image: "assets/quiz-images/earth-q39.jpg" },
    { text: "Which layer of Earth is the hottest?", options: ["Crust", "Mantle", "Outer Core", "Inner Core"], answerIndex: 3, image: "assets/quiz-images/earth-q40.jpg" },
    { text: "What is the study of weather called?", options: ["Geology", "Meteorology", "Astronomy", "Oceanography"], answerIndex: 1, image: "assets/quiz-images/earth-q41.jpg" },
    { text: "Which planet has the most moons?", options: ["Earth", "Mars", "Jupiter", "Saturn"], answerIndex: 3, image: "assets/quiz-images/earth-q42.jpg" },
    { text: "What is the largest mountain range on Earth?", options: ["Rockies", "Andes", "Himalayas", "Alps"], answerIndex: 2, image: "assets/quiz-images/earth-q43.jpg" },
    { text: "What causes an earthquake?", options: ["Wind", "Tectonic Plates", "Volcano", "Rain"], answerIndex: 1, image: "assets/quiz-images/earth-q44.jpg" },
    { text: "Which planet is known for its rings?", options: ["Jupiter", "Neptune", "Uranus", "Saturn"], answerIndex: 3, image: "assets/quiz-images/earth-q45.jpg" },
    { text: "What is the driest desert on Earth?", options: ["Sahara", "Gobi", "Atacama", "Kalahari"], answerIndex: 2 },
    { text: "How long does it take Earth to orbit the Sun?", options: ["One Day", "One Month", "One Year", "One Decade"], answerIndex: 2 },
    { text: "What gas makes up most of Earth's atmosphere?", options: ["Oxygen", "CO2", "Nitrogen", "Argon"], answerIndex: 2 },
    { text: "What is a large body of ice moving slowly called?", options: ["Iceberg", "Glacier", "Ice Sheet", "Snowcap"], answerIndex: 1 },
    { text: "Which planet is the smallest in our solar system?", options: ["Mars", "Venus", "Mercury", "Pluto"], answerIndex: 2 },
    { text: "What is the Ring of Fire?", options: ["Volcano Zone", "Mountain Range", "Ocean Current", "Desert"], answerIndex: 0 },
    { text: "How many planets in our solar system?", options: ["7", "8", "9", "10"], answerIndex: 1 },
    { text: "What is a sudden flash of light in a storm called?", options: ["Thunder", "Lightning", "Rain", "Wind"], answerIndex: 1 },
    { text: "Which layer of the atmosphere contains the ozone layer?", options: ["Troposphere", "Stratosphere", "Mesosphere", "Thermosphere"], answerIndex: 1 },
    { text: "What type of eclipse blocks the Sun?", options: ["Lunar", "Solar", "Partial", "Total"], answerIndex: 1 },
  ],
  'human-body': [
    { text: "What is the largest organ in the human body?", options: ["Liver", "Brain", "Heart", "Skin"], answerIndex: 3, image: "assets/quiz-images/human-body-q46.jpg" },
    { text: "How many bones are in the adult human body?", options: ["186", "196", "206", "216"], answerIndex: 2, image: "assets/quiz-images/human-body-q47.jpg" },
    { text: "What is the strongest muscle in the human body?", options: ["Biceps", "Heart", "Glutes", "Masseter"], answerIndex: 3, image: "assets/quiz-images/human-body-q48.jpg" },
    { text: "Which part of the brain controls balance?", options: ["Frontal Lobe", "Cerebellum", "Brain Stem", "Temporal Lobe"], answerIndex: 1, image: "assets/quiz-images/human-body-q49.jpg" },
    { text: "What blood type is the universal donor?", options: ["A", "B", "AB", "O"], answerIndex: 3, image: "assets/quiz-images/human-body-q50.jpg" },
    { text: "How many chambers does the human heart have?", options: ["2", "3", "4", "5"], answerIndex: 2, image: "assets/quiz-images/human-body-q51.jpg" },
    { text: "Which sense is associated with the tongue?", options: ["Smell", "Taste", "Touch", "Sight"], answerIndex: 1, image: "assets/quiz-images/human-body-q52.jpg" },
    { text: "What is the longest bone in the human body?", options: ["Tibia", "Femur", "Humerus", "Spine"], answerIndex: 1, image: "assets/quiz-images/human-body-q53.jpg" },
    { text: "Which vitamin is produced by sunlight?", options: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], answerIndex: 3, image: "assets/quiz-images/human-body-q54.jpg" },
    { text: "What percentage of the human body is water?", options: ["40%", "50%", "60%", "70%"], answerIndex: 2, image: "assets/quiz-images/human-body-q55.jpg" },
    { text: "Which organ filters waste from blood?", options: ["Liver", "Kidneys", "Lungs", "Stomach"], answerIndex: 1, image: "assets/quiz-images/human-body-q56.jpg" },
    { text: "What is the smallest bone in the human body?", options: ["Stapes", "Hammer", "Anvil", "Cochlea"], answerIndex: 0, image: "assets/quiz-images/human-body-q57.jpg" },
    { text: "Which part of the eye controls light entry?", options: ["Lens", "Retina", "Pupil", "Cornea"], answerIndex: 2, image: "assets/quiz-images/human-body-q58.jpg" },
    { text: "What are the cells that fight infection called?", options: ["Red Blood Cells", "White Blood Cells", "Platelets", "Plasma"], answerIndex: 1, image: "assets/quiz-images/human-body-q59.jpg" },
    { text: "Which organ pumps blood throughout the body?", options: ["Liver", "Lungs", "Brain", "Heart"], answerIndex: 3, image: "assets/quiz-images/human-body-q60.jpg" },
    { text: "What is the normal human body temperature in Celsius?", options: ["36°C", "37°C", "38°C", "39°C"], answerIndex: 1 },
    { text: "How many teeth does an adult human have?", options: ["28", "30", "32", "34"], answerIndex: 2 },
    { text: "What is the body's largest internal organ?", options: ["Heart", "Liver", "Lungs", "Stomach"], answerIndex: 1 },
    { text: "Which system controls breathing?", options: ["Circulatory", "Respiratory", "Digestive", "Nervous"], answerIndex: 1 },
    { text: "What connects muscles to bones?", options: ["Ligaments", "Tendons", "Cartilage", "Joints"], answerIndex: 1 },
    { text: "How many lungs does a human have?", options: ["1", "2", "3", "4"], answerIndex: 1 },
    { text: "What is the body's fastest healing tissue?", options: ["Bone", "Skin", "Muscle", "Nerve"], answerIndex: 1 },
    { text: "Which part of the body produces insulin?", options: ["Liver", "Pancreas", "Kidney", "Stomach"], answerIndex: 1 },
    { text: "What are the tiny air sacs in lungs called?", options: ["Bronchi", "Alveoli", "Trachea", "Diaphragm"], answerIndex: 1 },
    { text: "Which system includes the brain and spinal cord?", options: ["Skeletal", "Nervous", "Muscular", "Digestive"], answerIndex: 1 },
  ],
};

const IMAGE_CACHE_URLS = Object.values(QUESTION_BANKS)
  .flat().filter(q => q.image).map(q => q.image);
